### ISSUE TITLE
No output generated

### ISSUE THREAD

**Issue by jtadmor** [crysislinux/chrome-react-perf#2]
Hi,

This tool looks awesome, but I can't get it to work.

I'm using it by:

```
import Perf from 'react-addons-perf'
window.Perf = Perf
```

I start, make some changes, stop. All I see is:

<img width="1402" alt="screen shot 2016-04-12 at 4 53 20 pm" src="https://cloud.githubusercontent.com/assets/8089974/14478007/20279836-00cf-11e6-98f0-7acf80cc6ded.png">

I am using this with react 15.0.1, Chrome 49.0.2623 if that helps.

**Comment by crysislinux** [comment]
seems not compatible with v15 now. 
the extension uses a different version of react-addons-perf
I am trying to fix it.

**Comment by crysislinux** [comment]
It should work now.

Notice:  printDOM is deprecated in React v15, and printOperations is suggested.

It still called dom in the extension, but it is operations in fact if React v15 is used.

Let me know if you meet problems :)

**Comment by jtadmor** [comment]
I'm still seeing the same. Tried uninstalling and reinstalling the plugin and hard refresh browser, no luck.

**Comment by crysislinux** [comment]
I cannot reproduce the problem. Could you send me a minimal sample of your code?

I tested with:
- react 15.0.1
- react-addons-perf 15.0.1
- Chrome 49.0.2623
- chrome-react-perf 1.10

![image](https://cloud.githubusercontent.com/assets/5404597/14512578/e6fa51b2-0212-11e6-9464-d0d4fae62cf7.png)

One more thing. At least one component should rerender during the recording. 

Please try to manually type Perf.start()  Perf.stop() and Perf.printOperations in the console.

The extension should show the same thing as the console.

**Comment by jtadmor** [comment]
This is manually doing it in the console:

<img width="1393" alt="screen shot 2016-04-13 at 5 54 09 pm" src="https://cloud.githubusercontent.com/assets/8089974/14512927/bfeb98b4-01a0-11e6-8ff3-e0635abf46db.png">

Clicking the same buttons while recording does not produce any output.

What code would you be wanting to see? 

(Edit to add: Not trying to be a pain, dont feel the need to reply or anything, I may look through the code this weekend myself).

**Comment by andyg303** [comment]
Just to chip in with my experience, 15.0.0 didn't work for me. If I go back to 0.14.8 or forward to 15.0.1 the print outs started working again.

Thanks!

**Comment by FionaWong** [comment]
I meet the same question now, sometimes it works as the Landlord printed, sometimes it returns like 

<img width="618" alt="2016-11-21 2 33 52" src="https://cloud.githubusercontent.com/assets/2347438/20472876/d39fe81e-aff7-11e6-9aa4-b9ddc28f6117.png">

but still no wasted print, I can not believe there is no wasted in the application.

react@0.14.8
react-dom@0.14.8
React Perf 1.1.0
chrome  54.0.2840.98 (64-bit)

thanks.

**Comment by react-state** [comment]
Hello, I have faced same issue - no wasted output. But this is the same from console and from extension.
![react](https://cloud.githubusercontent.com/assets/27964623/26547592/66e734f0-4478-11e7-8032-bdac83a39631.png)
